#!/bin/bash
#--------------------------------------------------------------------------------
#################################################################################
#--------------------------------------------------------------------------------
ERROR_LOG="error.log"; [ -f "${ERROR_LOG}" ] && rm "${ERROR_LOG}"
#--------------------------------------------------------------------------------
STDOUT=$(mktemp); STDERR=$(mktemp)
#--------------------------------------------------------------------------------
zig-run >"${STDOUT}" 2>"${STDERR}"
#--------------------------------------------------------------------------------
[ -s "${STDOUT}" ] && OUTPUT=$(cat "${STDOUT}"); [ ! -s "${STDOUT}" ] && OUTPUT=$(cat "${STDERR}")
#--------------------------------------------------------------------------------
[[ ! "${OUTPUT}" =~ "test case 1 should pass" ]] && echo "(${LINENO}) test case 1 should pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "test case 2 should fail" ]] && echo "(${LINENO}) test case 2 should fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "test case 3 should pass" ]] && echo "(${LINENO}) test case 3 should pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "test case 4 should fail" ]] && echo "(${LINENO}) test case 4 should fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "test case 5 should pass" ]] && echo "(${LINENO}) test case 5 should pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "test case 6 should fail" ]] && echo "(${LINENO}) test case 6 should fail" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "test case 7 should pass" ]] && echo "(${LINENO}) test case 7 should pass" >> ${ERROR_LOG}
[[ ! "${OUTPUT}" =~ "test case 8 should fail" ]] && echo "(${LINENO}) test case 8 should fail" >> ${ERROR_LOG}
#--------------------------------------------------------------------------------
if [ -f ${ERROR_LOG} ]
then
    cat ${ERROR_LOG} >&2
else
    echo "no errors detected"
fi
#--------------------------------------------------------------------------------
[ -f "${STDOUT}" ] && rm "${STDOUT}"
[ -f "${STDERR}" ] && rm "${STDERR}"
[ -f "${ERROR_LOG}" ] && rm "${ERROR_LOG}"
#--------------------------------------------------------------------------------
exit 0
#--------------------------------------------------------------------------------
#################################################################################
#--------------------------------------------------------------------------------
