version: '3'

vars:
  SOURCE: "main.zig"
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"
  OUTPUT:
    sh: |
      if [[ "{{OS}}" == "windows" ]]; then
        echo ${PWD##*\\}
      else
        basename "${PWD}"
      fi

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig build-exe ../{{.SOURCE}} -femit-bin={{.OUTPUT}} -fstrip -O ReleaseSmall -target x86_64-apple-darwin -mcpu=baseline

  build-darwin:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig build-exe ../{{.SOURCE}} -femit-bin={{.OUTPUT}}-darwin -fstrip -O ReleaseSmall -target x86_64-macos -mcpu=baseline

  build-linux:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig build-exe ../{{.SOURCE}} -femit-bin={{.OUTPUT}} -fstrip -O ReleaseSmall -target x86_64-linux -mcpu=baseline

  build-windows:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig build-exe ../{{.SOURCE}} -femit-bin={{.OUTPUT}}-windows.exe -fstrip -O ReleaseSmall -target x86_64-windows -mcpu=baseline

  run:
    cmds:
      - silent: true
        cmd: |
          if [ -x "{{.OUTPUT_PATH}}/{{.OUTPUT}}" ]; then
            "{{.OUTPUT_PATH}}/{{.OUTPUT}}" {{.CLI_ARGS}}
          else
            zig run {{.SOURCE}} -- {{.CLI_ARGS}}
          fi

