version: "3"

vars:
  OUTPUT_PATH: "zig-out"
  OUTPUT:
    sh: |
      if [[ "{{OS}}" == "windows" ]]; then
        echo ${PWD##*\\}
      else
        basename "${PWD}"
      fi

tasks:
  clean:
    cmds:
      - rm -rf {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig build-exe ../main.zig  -femit-bin={{.OUTPUT}} -fstrip -O ${ZIG_BUILD_MODE} -target native -mcpu=baseline

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - silent: true
        cmd: |
          if [ -x "{{.OUTPUT}}" ]; then
            ./{{.OUTPUT}} {{.CLI_ARGS}}
          else
            zig run ../main.zig -- {{.CLI_ARGS}}
          fi