version: '3'

vars:
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig build-lib ../math.zig -femit-bin=libmath.so -dynamic -fstrip -O ReleaseSmall -target native -mcpu=baseline
      - zig build-exe ../main.zig -femit-bin=zigmain -fstrip -lc -L. -lmath -O ReleaseSmall -target native -mcpu=baseline
      - patchelf --replace-needed liblibmath.so ./libmath.so ./zigmain
      - gcc -o cmain ../main.c -L. -lmath -Wl,-rpath=.
      - rm -rf libmath.so.o zigmain.o

  run:
    deps: [build]
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - ./cmain {{.CLI_ARGS}}
      - ./zigmain {{.CLI_ARGS}}
