version: '3'

vars:
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig build -Doptimize=ReleaseSmall -Dtarget=native -Dcpu=baseline
      - rm -rf ../{{.CACHE_PATH}} bin lib

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - ./lib-cc-dynlib-build {{.CLI_ARGS}}
