version: '3'

vars:
  CACHE_PATH: ".zig-cache"
  OUTPUT_PATH: "zig-out"

tasks:
  clean:
    cmds:
      - rm -rf {{.CACHE_PATH}} {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - zig build-exe ../main.zig -femit-bin=libc-printf -lc -fstrip -O ReleaseSmall -target native -mcpu=baseline
      - rm libc-printf.o

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - ./libc-printf {{.CLI_ARGS}}
